gpus: 1
hop_length: 512
sequence_length: 327680
sampling_rate: 16000
data_root: './dataset'
checkpoint_path: '/scratch/negishi/kumar809/skum156-DiffRoll/Pretrain_MAESTRO-retrain_Both-k=9.ckpt'

dataloader:
    batch_size: 4
    num_workers: 0 # <--- CHANGE THIS TO 0
    shuffle: False
    pin_memory: True

task:
    sampling:
        type: transcription # Corrected for transcription
    frame_threshold: 0.8
    generation_filter: 0.1
    inpainting_t: null
    inpainting_f: null

trainer:
    accelerator: cpu
    gpus: 0

defaults:
    - model: ClassifierFreeDiffRoll

dataset:
  name: Custom
  num_samples: ${dataloader.batch_size}
  args:
    audio_path: '/scratch/negishi/kumar809/skum156-DiffRoll/inputs' # Corrected folder path
    audio_ext: mp3
    max_segment_samples: 327680
    # ... any other args ...